In [1]:
pip install faker

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: faker in c:\users\shiva\appdata\roaming\python\python313\site-packages (40.31.0)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from faker) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import json
import sqlite3
import random
import logging

from faker import Faker

In [6]:
fake = Faker()

In [9]:
customers = []

for i in range(1000):

    customers.append({
        "CustomerID": i + 1,
        "Name": fake.name(),
        "Email": fake.email(),
        "Age": random.randint(18, 65),
        "City": fake.city()
    })

df = pd.DataFrame(customers)

df.head()

,CustomerID,Name,Email,Age,City
0,1,Stephanie Reed,smurphy@example.net,52,West Veronicaview
1,2,Deborah Jackson,leslie13@example.com,21,Port Jamestown
2,3,David Wagner,mary73@example.com,51,Yorkville
3,4,Sarah Boyer,hodgeseric@example.net,41,South Melanieshire
4,5,Julie Hall,huntertimothy@example.org,33,Cuevasmouth

In [10]:
df.shape

(1000, 5)

In [11]:
df.to_csv("customers.csv", index=False)

print("Customer dataset saved successfully.")

Customer dataset saved successfully.

In [12]:
df.loc[5, "Email"] = None

df.loc[20, "Age"] = "Unknown"

df.loc[35, "CustomerID"] = None

df.to_csv("customers.csv", index=False)

df.head(40)

C:\Users\shiva\AppData\Local\Temp\ipykernel_23284\1580066259.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[20, "Age"] = "Unknown"

,CustomerID,Name,Email,Age,City
0,1.0,Stephanie Reed,smurphy@example.net,52,West Veronicaview
1,2.0,Deborah Jackson,leslie13@example.com,21,Port Jamestown
2,3.0,David Wagner,mary73@example.com,51,Yorkville
3,4.0,Sarah Boyer,hodgeseric@example.net,41,South Melanieshire
4,5.0,Julie Hall,huntertimothy@example.org,33,Cuevasmouth
5,6.0,Sean Cortez,None,19,Armstrongchester
6,7.0,Sabrina Baker,nataliemoore@example.net,41,North Robert
7,8.0,Mallory English,claire84@example.net,32,Port Cynthia
8,9.0,Timothy Garcia,philliproberts@example.com,46,New Dawn
9,10.0,Wanda Reid,aedwards@example.com,60,Port Julie
10,11.0,Frank Martinez,grosschristian@example.net,54,West Joshualand
11,12.0,Shawn Owens,amiller@example.net,18,Ramirezport
12,13.0,Christina Reynolds,danielbaker@example.org,61,Lake Brandonland
13,14.0,David Ramos,robyntodd@example.org,44,New Karenberg
14,15.0,Mark Carson,balvarez@example.com,26,North Alexandra
15,16.0,Rhonda Robertson,sara05@example.net,43,Bradleyland
16,17.0,James Smith,ryan09@example.org,47,Jenniferville
17,18.0,Kristina Chase,tphillips@example.net,65,Lake Tylerfort
18,19.0,Danielle Hall,twilliams@example.org,56,South Lindseyville
19,20.0,Shari Gardner,andradesusan@example.net,30,West Derrick
20,21.0,Jill Benton,gdavis@example.org,Unknown,Byrdshire
21,22.0,Sean Harris,christopher21@example.org,46,Jenniferview
22,23.0,William Gibson,jacquelinerowe@example.com,20,East Michaelshire
23,24.0,Jonathan Taylor,romeromichael@example.com,55,New Scott
24,25.0,Dawn Walker,nicolerodriguez@example.com,39,Stephensville
25,26.0,Tracy Parsons,hickserika@example.com,21,Erinmouth
26,27.0,Derek Rodriguez,christine07@example.net,50,South Dean
27,28.0,Diana Wood,veronicakelly@example.com,55,Lake Carlyview
28,29.0,Allison Clark,karl44@example.com,61,Shawnhaven
29,30.0,Theresa Nguyen,ashley07@example.org,36,Garrettshire
30,31.0,April Martin,dale06@example.net,45,North Charlesmouth
31,32.0,Brittany Pollard,nmarks@example.net,34,Tylerborough
32,33.0,Stephanie Perez,idillon@example.com,21,Mikeland
33,34.0,Kyle Bishop,taylorjason@example.net,31,Brandonborough
34,35.0,David Wallace,scott01@example.com,20,Riveraview
35,NaN,Beth Jackson,santanasusan@example.com,57,Hudsonchester
36,37.0,Samantha Adams,christielevy@example.net,50,New Janetfurt
37,38.0,Anne Vega,david41@example.org,29,Welchmouth
38,39.0,John Salinas,sleon@example.net,61,Amandaport
39,40.0,Monica Smith,bflores@example.com,29,Whiteton

In [14]:
df = pd.read_csv("customers.csv")

df.head(40)

,CustomerID,Name,Email,Age,City
0,1.0,Stephanie Reed,smurphy@example.net,52,West Veronicaview
1,2.0,Deborah Jackson,leslie13@example.com,21,Port Jamestown
2,3.0,David Wagner,mary73@example.com,51,Yorkville
3,4.0,Sarah Boyer,hodgeseric@example.net,41,South Melanieshire
4,5.0,Julie Hall,huntertimothy@example.org,33,Cuevasmouth
5,6.0,Sean Cortez,NaN,19,Armstrongchester
6,7.0,Sabrina Baker,nataliemoore@example.net,41,North Robert
7,8.0,Mallory English,claire84@example.net,32,Port Cynthia
8,9.0,Timothy Garcia,philliproberts@example.com,46,New Dawn
9,10.0,Wanda Reid,aedwards@example.com,60,Port Julie
10,11.0,Frank Martinez,grosschristian@example.net,54,West Joshualand
11,12.0,Shawn Owens,amiller@example.net,18,Ramirezport
12,13.0,Christina Reynolds,danielbaker@example.org,61,Lake Brandonland
13,14.0,David Ramos,robyntodd@example.org,44,New Karenberg
14,15.0,Mark Carson,balvarez@example.com,26,North Alexandra
15,16.0,Rhonda Robertson,sara05@example.net,43,Bradleyland
16,17.0,James Smith,ryan09@example.org,47,Jenniferville
17,18.0,Kristina Chase,tphillips@example.net,65,Lake Tylerfort
18,19.0,Danielle Hall,twilliams@example.org,56,South Lindseyville
19,20.0,Shari Gardner,andradesusan@example.net,30,West Derrick
20,21.0,Jill Benton,gdavis@example.org,Unknown,Byrdshire
21,22.0,Sean Harris,christopher21@example.org,46,Jenniferview
22,23.0,William Gibson,jacquelinerowe@example.com,20,East Michaelshire
23,24.0,Jonathan Taylor,romeromichael@example.com,55,New Scott
24,25.0,Dawn Walker,nicolerodriguez@example.com,39,Stephensville
25,26.0,Tracy Parsons,hickserika@example.com,21,Erinmouth
26,27.0,Derek Rodriguez,christine07@example.net,50,South Dean
27,28.0,Diana Wood,veronicakelly@example.com,55,Lake Carlyview
28,29.0,Allison Clark,karl44@example.com,61,Shawnhaven
29,30.0,Theresa Nguyen,ashley07@example.org,36,Garrettshire
30,31.0,April Martin,dale06@example.net,45,North Charlesmouth
31,32.0,Brittany Pollard,nmarks@example.net,34,Tylerborough
32,33.0,Stephanie Perez,idillon@example.com,21,Mikeland
33,34.0,Kyle Bishop,taylorjason@example.net,31,Brandonborough
34,35.0,David Wallace,scott01@example.com,20,Riveraview
35,NaN,Beth Jackson,santanasusan@example.com,57,Hudsonchester
36,37.0,Samantha Adams,christielevy@example.net,50,New Janetfurt
37,38.0,Anne Vega,david41@example.org,29,Welchmouth
38,39.0,John Salinas,sleon@example.net,61,Amandaport
39,40.0,Monica Smith,bflores@example.com,29,Whiteton

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  999 non-null    float64
 1   Name        1000 non-null   object
 2   Email       999 non-null    object
 3   Age         1000 non-null   object
 4   City        1000 non-null   object
dtypes: float64(1), object(4)
memory usage: 39.2+ KB

In [16]:
df.dtypes

CustomerID    float64
Name           object
Email          object
Age            object
City           object
dtype: object

In [20]:
df.describe(include="all")

,CustomerID,Name,Email,Age,City
count,999.000000,1000,999,1000,1000
unique,NaN,989,995,49,960
top,NaN,Christina Smith,mjackson@example.com,31,Christophermouth
freq,NaN,2,2,31,3
mean,500.964965,NaN,NaN,NaN,NaN
std,288.589399,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN
25%,251.500000,NaN,NaN,NaN,NaN
50%,501.000000,NaN,NaN,NaN,NaN
75%,750.500000,NaN,NaN,NaN,NaN
max,1000.000000,NaN,NaN,NaN,NaN

In [21]:
df.isnull().sum()

CustomerID    1
Name          0
Email         1
Age           0
City          0
dtype: int64

In [22]:
schema = df.dtypes

print(schema)

CustomerID    float64
Name           object
Email          object
Age            object
City           object
dtype: object

In [23]:
expected_schema = {

    "CustomerID": "float64",

    "Name": "object",

    "Email": "object",

    "Age": "int64",

    "City": "object"

}

In [24]:
for column in expected_schema:

    print(column)

    print("Expected :", expected_schema[column])

    print("Actual   :", df[column].dtype)

    print()

CustomerID
Expected : float64
Actual   : float64

Name
Expected : object
Actual   : object

Email
Expected : object
Actual   : object

Age
Expected : int64
Actual   : object

City
Expected : object
Actual   : object

In [25]:
missing_pk = df[df["CustomerID"].isnull()]

missing_pk

    CustomerID          Name                     Email Age           City
35         NaN  Beth Jackson  santanasusan@example.com  57  Hudsonchester

In [26]:
missing_email = df[df["Email"].isnull()]

missing_email

   CustomerID         Name Email Age              City
5         6.0  Sean Cortez   NaN  19  Armstrongchester

In [28]:
invalid_age = df[df["Age"] == "Unknown"]

invalid_age

    CustomerID         Name               Email      Age       City
20        21.0  Jill Benton  gdavis@example.org  Unknown  Byrdshire

In [29]:
bad_records = df[

    df["CustomerID"].isnull()

    |

    df["Email"].isnull()

    |

    (df["Age"] == "Unknown")

]

bad_records

,CustomerID,Name,Email,Age,City
5,6.0,Sean Cortez,NaN,19,Armstrongchester
20,21.0,Jill Benton,gdavis@example.org,Unknown,Byrdshire
35,NaN,Beth Jackson,santanasusan@example.com,57,Hudsonchester

In [30]:
bad_records.to_csv("quarantine.csv", index=False)

print("Quarantine file created.")

Quarantine file created.

In [32]:
good_records = df.drop(bad_records.index)

good_records.head(40)

,CustomerID,Name,Email,Age,City
0,1.0,Stephanie Reed,smurphy@example.net,52,West Veronicaview
1,2.0,Deborah Jackson,leslie13@example.com,21,Port Jamestown
2,3.0,David Wagner,mary73@example.com,51,Yorkville
3,4.0,Sarah Boyer,hodgeseric@example.net,41,South Melanieshire
4,5.0,Julie Hall,huntertimothy@example.org,33,Cuevasmouth
6,7.0,Sabrina Baker,nataliemoore@example.net,41,North Robert
7,8.0,Mallory English,claire84@example.net,32,Port Cynthia
8,9.0,Timothy Garcia,philliproberts@example.com,46,New Dawn
9,10.0,Wanda Reid,aedwards@example.com,60,Port Julie
10,11.0,Frank Martinez,grosschristian@example.net,54,West Joshualand
11,12.0,Shawn Owens,amiller@example.net,18,Ramirezport
12,13.0,Christina Reynolds,danielbaker@example.org,61,Lake Brandonland
13,14.0,David Ramos,robyntodd@example.org,44,New Karenberg
14,15.0,Mark Carson,balvarez@example.com,26,North Alexandra
15,16.0,Rhonda Robertson,sara05@example.net,43,Bradleyland
16,17.0,James Smith,ryan09@example.org,47,Jenniferville
17,18.0,Kristina Chase,tphillips@example.net,65,Lake Tylerfort
18,19.0,Danielle Hall,twilliams@example.org,56,South Lindseyville
19,20.0,Shari Gardner,andradesusan@example.net,30,West Derrick
21,22.0,Sean Harris,christopher21@example.org,46,Jenniferview
22,23.0,William Gibson,jacquelinerowe@example.com,20,East Michaelshire
23,24.0,Jonathan Taylor,romeromichael@example.com,55,New Scott
24,25.0,Dawn Walker,nicolerodriguez@example.com,39,Stephensville
25,26.0,Tracy Parsons,hickserika@example.com,21,Erinmouth
26,27.0,Derek Rodriguez,christine07@example.net,50,South Dean
27,28.0,Diana Wood,veronicakelly@example.com,55,Lake Carlyview
28,29.0,Allison Clark,karl44@example.com,61,Shawnhaven
29,30.0,Theresa Nguyen,ashley07@example.org,36,Garrettshire
30,31.0,April Martin,dale06@example.net,45,North Charlesmouth
31,32.0,Brittany Pollard,nmarks@example.net,34,Tylerborough
32,33.0,Stephanie Perez,idillon@example.com,21,Mikeland
33,34.0,Kyle Bishop,taylorjason@example.net,31,Brandonborough
34,35.0,David Wallace,scott01@example.com,20,Riveraview
36,37.0,Samantha Adams,christielevy@example.net,50,New Janetfurt
37,38.0,Anne Vega,david41@example.org,29,Welchmouth
38,39.0,John Salinas,sleon@example.net,61,Amandaport
39,40.0,Monica Smith,bflores@example.com,29,Whiteton
40,41.0,William Chan,williamprice@example.org,65,Bradshawfurt
41,42.0,Jared Lucas,christophernguyen@example.org,45,Tammyside
42,43.0,David Campbell,scotterika@example.net,61,Hernandezville

In [34]:
good_records.shape

(997, 5)

In [35]:
logging.basicConfig(

    filename="ingestion.log",

    level=logging.INFO,

    format="%(asctime)s - %(levelname)s - %(message)s"

)

In [37]:
logging.info("Customer dataset loaded.")

logging.warning("Missing Email detected.")

logging.warning("Missing CustomerID detected.")

logging.warning("Invalid Age format detected.")

logging.info("Bad records moved to quarantine.")

In [39]:
transactions = []

for i in range(1500):

    transactions.append({

        "transaction_id": i + 1,

        "customer": {

            "id": random.randint(1, 200),

            "name": fake.name()

        },

        "payment": {

            "amount": random.randint(100, 5000),

            "mode": random.choice(["UPI", "Card", "Cash"])

        }

    })

In [40]:
with open("api_logs.json", "w") as file:

    json.dump(transactions, file, indent=4)

print("JSON file created.")

JSON file created.

In [41]:
with open("api_logs.json") as file:

    data = json.load(file)

In [42]:
api_df = pd.json_normalize(data)

api_df.head()

,transaction_id,customer.id,customer.name,payment.amount,payment.mode
0,1,187,David Franklin,1940,Card
1,2,175,Daniel Glenn,4730,UPI
2,3,147,Mrs. Andrea Johnson MD,795,Cash
3,4,171,Sarah Wilson,861,Card
4,5,77,Emily Phillips,1313,Card

In [43]:
api_df.shape

(1500, 5)

In [44]:
api_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  1500 non-null   int64
 1   customer.id     1500 non-null   int64
 2   customer.name   1500 non-null   object
 3   payment.amount  1500 non-null   int64
 4   payment.mode    1500 non-null   object
dtypes: int64(3), object(2)
memory usage: 58.7+ KB

In [45]:
config = """

Server=localhost

Port=5432

Timeout=30

Cache=True

Random Text

Unknown Line

"""

with open("config.txt", "w") as file:

    file.write(config)

In [46]:
with open("config.txt") as file:

    lines = file.readlines()

for line in lines:

    if "=" in line:

        print("Valid :", line.strip())

    else:

        print("Invalid :", line.strip())

Invalid :
Invalid :
Valid : Server=localhost
Invalid :
Valid : Port=5432
Invalid :
Valid : Timeout=30
Invalid :
Valid : Cache=True
Invalid :
Invalid : Random Text
Invalid :
Invalid : Unknown Line
Invalid :

In [47]:
conn = sqlite3.connect("customer.db")

good_records.to_sql(

    "Customers",

    conn,

    if_exists="replace",

    index=False

)

997

In [48]:
pd.read_sql("SELECT * FROM Customers", conn)

,CustomerID,Name,Email,Age,City
0,1.0,Stephanie Reed,smurphy@example.net,52,West Veronicaview
1,2.0,Deborah Jackson,leslie13@example.com,21,Port Jamestown
2,3.0,David Wagner,mary73@example.com,51,Yorkville
3,4.0,Sarah Boyer,hodgeseric@example.net,41,South Melanieshire
4,5.0,Julie Hall,huntertimothy@example.org,33,Cuevasmouth
...,...,...,...,...,...
992,996.0,Lindsey Johnson,bennettmorgan@example.org,42,West Gabrielleview
993,997.0,Monica Davis,smithjasmine@example.net,65,Keithmouth
994,998.0,Bryan Douglas,rachel76@example.com,60,North Alexander
995,999.0,Lauren Sanchez,nelsonlynn@example.net,45,Jamesbury
996,1000.0,Cole Watts,bmorris@example.org,20,Clinebury

In [49]:
summary = {

    "Total Records": len(df),

    "Valid Records": len(good_records),

    "Invalid Records": len(bad_records),

    "Missing Email": df["Email"].isnull().sum(),

    "Missing CustomerID": df["CustomerID"].isnull().sum()

}

summary

{'Total Records': 1000,
 'Valid Records': 997,
 'Invalid Records': 3,
 'Missing Email': np.int64(1),
 'Missing CustomerID': np.int64(1)}